<?php

namespace Nsm\Bundle\HelpBundle\Entity;

use Nsm\Bundle\CoreBundle\Entity\AbstractRepository;

/**
 * TipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipRepository extends AbstractRepository
{
}
