Nsm\Bundle\UserBundle\Entity\User:
    type: entity
    table: NsmUser
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        mailboxHash:
            type: string
            length: 255
        timeZone:
            type: timezone
            nullable: true
        locale:
            type: string
            length: 6
            nullable: true
        githubId:
            type: string
            nullable: true
        instagramId:
            type: string
            nullable: true
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        deletedAt:
            type: datetime
            nullable: true
    oneToMany:
        invitations:
            targetEntity: Nsm\Bundle\ApiBundle\Entity\Invitation
            mappedBy: claimedBy
            cascade:
                - remove
    lifecycleCallbacks:
        prePersist:
            - resetMailboxHash
    serializer:
        exclusion_policy: ALL
        xml_root_name: user
        custom_accessor_order:
            - id
