Nsm\Bundle\ApiBundle\Entity\Activity:
    type: entity
    table: activity
    repositoryClass: Nsm\Bundle\ApiBundle\Entity\ActivityRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        task:
            targetEntity: Task
            inversedBy: activities
