parameters:

    club_evo_api.entity.service_center_group_employee.class: ClubEvo\Bundle\ApiBundle\Entity\ServiceCenterGroupEmployee
    club_evo_api.entity.service_center_group_employee_manager.class: ClubEvo\Bundle\ApiBundle\Entity\ServiceCenterGroupEmployeeManager
    club_evo_api.entity.service_center_group_employee_repository.class: ClubEvo\Bundle\ApiBundle\Entity\ServiceCenterGroupEmployeeRepository
    club_evo_api.event_subscriber.service_center_group_employee_subscriber.class: ClubEvo\Bundle\ApiBundle\EventSubscriber\ServiceCenterGroupEmployeeSubscriber

services:

    club_evo_api.entity.service_center_group_employee_manager:
        class: %club_evo_api.entity.service_center_group_employee_manager.class%
        arguments: [%club_evo_api.entity.service_center_group_employee.class%, @doctrine.orm.entity_manager]

    club_evo_api.entity.service_center_group_employee_repository:
        class: %club_evo_api.entity.service_center_group_employee_repository.class%
        factory_service: "doctrine.orm.entity_manager"
        factory_method: "getRepository"
        arguments: [%club_evo_api.entity.service_center_group_employee.class%]

    club_evo_api.event_subscriber.service_center_group_employee_subscriber:
        class: %club_evo_api.event_subscriber.service_center_group_employee_subscriber.class%
        arguments: [@service_container]
        tags:
          - {name: "doctrine.event_subscriber", connection: "default"}
