ClubEvo\Bundle\ApiBundle\Entity\Organisation:
    type: mappedSuperclass
    table: organisation
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
    fields:
        title:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        acn:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        abn:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        type:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        class:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        subclass:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: subClass
    oneToOne:
        contactCard:
            targetEntity: Nsm\Bundle\ContactCardBundle\Entity\ContactCard
            cascade: {  }
            mappedBy: contactCard
            inversedBy: null
            joinColumns:
                ContactCard_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
