
imports:
    - { resource: "services/entities/Activity.yml" }
    - { resource: "services/entities/Project.yml" }
    - { resource: "services/entities/Task.yml" }
    - { resource: "services/entities/Invitation.yml" }
    - { resource: "validations.yml" }
