Nsm\Bundle\ApiBundle\Entity\Project:
    properties:
        title:
            - NotBlank: ~
        taskDurationSum:
            - GreaterThanOrEqual:
                value: 0
        createdAt:
            - Date: ~
        updatedAt:
            - Date: ~
        deletedAt:
            - Date: ~
