<?php

namespace Nsm\Bundle\AppBundle\Entity;

use Nsm\Bundle\CoreBundle\Entity\AbstractRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends AbstractRepository
{
}
