Nsm\Bundle\ApiBundle\Entity\Invitation:
    exclusion_policy: ALL
    xml_root_name: invitation
    custom_accessor_order:
        - id
    relations:
        -
            rel: self
            href:
                route: invitation_read
                parameters:
                    id: expr(object.getId())
