Nsm\Bundle\ApiBundle\Entity\Activity:
    exclusion_policy: ALL
    xml_root_name: activity
    custom_accessor_order:
        - id
    properties:
        title:
            expose: true
        description:
            expose: true
    relations:
        -
            rel: self
            href:
                route: activity_read
                parameters:
                    id: expr(object.getId())
        -
            rel: task
            href:
                route: task_read
                parameters:
                    id: expr(object.getTask().getId())
            embedded:
                content: expr(object.getTask())
                xmlElementName: task
