<?php

namespace Nsm\Bundle\ApiBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends AbstractRepository
{
    /**
     * @param array $criteria
     * @param bool $removeEmpty
     * @return $this
     */
    public function sanatiseCriteria(array $criteria, $removeEmpty = true)
    {
//        if(true === isset($criteria['dateRange'])) {
//            $dateRange = $criteria['dateRange'];
//            $criteria['dateRange'] = array(
//                "startedAt" => $dateRange->getStart(),
//                "endedAt" => $dateRange->getEnd()
//            );
//        }
        return parent::sanatiseCriteria($criteria);
    }
}
