<?php

namespace Nsm\Bundle\ApiBundle\Entity;

use Nsm\Bundle\CoreBundle\Entity\AbstractRepository;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureRepository extends AbstractRepository
{
}
