<?php

namespace Nsm\Bundle\ApiBundle\Entity;

use Nsm\Bundle\CoreBundle\Entity\AbstractRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends AbstractRepository
{
}
